### ISSUE TITLE
PumpedStorage initialisation

### ISSUE THREAD

**Issue by jarry7** [NREL-SIIP/PowerSimulations.jl#888] opened 2022-12-02 03:27 UTC
**If this is a question, something isn't working or an idea please start a Q&A discussion in the [Discussion tab](https://github.com/NREL-SIIP/PowerSimulations.jl/discussions)**
Open a bug report only if you can provide the details below

**Describe the bug**
Custom HydroPumpedStorage when device model is HydroDispatchPumpedStorage seems to have specific initialisation issues.  Seemingly at the start of every 24 hour time step (3 example days shown)

<img width="300" alt="image" src="https://user-images.githubusercontent.com/27745389/205208126-734168c6-8b0f-45c6-8ffe-83d7c333c1ca.png">
<img width="300" alt="image" src="https://user-images.githubusercontent.com/27745389/205208161-f87995e0-65ca-48ee-a777-a8624f89e4ca.png">

**To Reproduce**
network_map = Dict(
    "DCPPowerModel" => PSI.DCPPowerModel,
    "CopperPlatePowerModel" => PSI.CopperPlatePowerModel,
    "NFAPowerModel" => PSI.NFAPowerModel,
    "StandardPTDFModel" => PSI.StandardPTDFModel
)
duals = Dict(
    "DCPPowerModel" => [NodalBalanceActiveConstraint],
    "CopperPlatePowerModel" => [CopperPlateBalanceConstraint],
    "NFAPowerModel" => [NodalBalanceActiveConstraint],
    "StandardPTDFModel" => [CopperPlateBalanceConstraint],
)
template = ProblemTemplate(NetworkModel(network_map[tx], duals=duals[tx], use_slacks=true, PTDF=ptdf))
set_device_model!(template, DeviceModel(HydroPumpedStorage, HydroDispatchPumpedStorage; attributes=Dict{String,Any}("reservation" => false)))
+ {other model devices set}
Custom model definition "RebuildOpProblem" (@sourabhdalvi for NTPS)
Simulation is 7 steps, 24 hour time horizon.

**Expected behavior**
Energy balance for pumped storage is respected and substantial charging at the beginning of every 24 hour period does not occur (initial conditions handover from previous day).

**Screenshots**

**Additional context**
Large system (000's of nodes).

**Comment by jd-lara** [comment] 2022-12-02 07:48
@jarry7 thanks for the report. It seems that there is an issue with the mechanism to pass the initial condition data as you helpfully pointed out.

**Comment by jd-lara** [comment] 2022-12-12 20:18
closing as duplicate of #886

**Closed by jd-lara** 2022-12-12 20:18 UTC
Labels: duplicate
